// Generated by Wrangler (run `wrangler types` to regenerate)
interface Env {
  DB: D1Database;
  ADMIN_PASSWORD_HASH: string;
  ADMIN_SESSION_SECRET: string;
  TURNSTILE_SITE_KEY: string;
  TURNSTILE_SECRET_KEY: string;
  ANDROID_API_SECRET: string;
  APP_URL: string;
}
